# Generated by Django 3.1.3 on 2020-12-01 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmppa',
            name='paperid',
            field=models.ForeignKey(db_column='PaperID', on_delete=django.db.models.deletion.CASCADE, to='apps.tmppaper'),
        ),
    ]
