# Generated by Django 3.1.3 on 2020-11-14 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_appsuserinfo_appsuserinfogroups_appsuserinfouserpermissions_authgroup_authgrouppermissions_author_au'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppsUserinfo',
        ),
        migrations.DeleteModel(
            name='AppsUserinfoGroups',
        ),
        migrations.DeleteModel(
            name='AppsUserinfoUserPermissions',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
