# Generated by Django 3.1.3 on 2020-11-25 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20201114_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paperfile',
            fields=[
                ('paperid', models.OneToOneField(db_column='PaperID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='apps.paper')),
                ('doc', models.TextField(db_column='Doc')),
            ],
            options={
                'db_table': 'PaperFile',
                'managed': False,
            },
        ),
    ]
