# Generated by Django 3.1 on 2020-11-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('paperid', models.IntegerField(db_column='paperID', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'demo',
                'managed': False,
            },
        ),
    ]
